version: '3.7'
services:
  devcontainer:
    build: .
    command: sh -x -c 'while :; do sleep 60; done'
    init: true
    volumes:
      - ..:/workspace
      - cabal:/home/haskell/.cabal
      - cabal-store:/cabal-store
    working_dir: /workspace
volumes:
  cabal: null
  cabal-store:
    external: true
