services:
  devcontainer:
    build: .
    command: sh -c 'while sleep 1; do :; done'
    init: true
    volumes:
      - ..:/workspace
      - cabal:/home/haskell/.cabal
      - cabal-store:/cabal-store
    working_dir: /workspace
volumes:
  cabal: null
  cabal-store:
    external: true
